name: Build and Deploy Documents.

on:
  push:
    branches: [ "main" ]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install Requirements.
      run: pip3 install sphinx sphinx_multiversion sphinx_rtd_theme myst-parser

    - name: Build
      run: |
        make mhtml
        tar -zcvf htmls.tar.gz build/**

    - name: Upload artifact
      uses: actions/upload-artifact@main
      with:
        name: github-pages
        path: htmls.tar.gz
        retention-days: '1'

  deploy:
    needs: build

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
