name: Release documents.

on:
  push:
    tags: [ "v*.*" ]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write

jobs:
  build-release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install Requirements.
      run: pip3 install sphinx sphinx_multiversion sphinx_rtd_theme myst-parser

    - name: Build
      run: |
        make mhtml
        find build -type d -name ".doctrees" | xargs rm -rf
        find build -type f -name ".buildinfo" | xargs rm -rf
        tar -zcvf htmls.tar.gz build/**

    - uses: ncipollo/release-action@v1
      with:
        artifacts: "htmls.tar.gz"
        token: ${{ secrets.GITHUB_TOKEN  }}
